telerik/document-processing-docs

libraries/radpdfprocessing/concepts/position.md

Small change in the comment of a sample code.

Update PdfProcessing Position

---

libraries/radspreadprocessing/getting-started.md

Formats and Conversion section linked in the Getting Started article.

Update information in Getting Strated for SpreadProcessing

---

libraries/radpdfprocessing/editing/block.md
libraries/radpdfprocessing/editing/fixedcontenteditor.md
libraries/radpdfprocessing/editing/radfixeddocumenteditor.md
libraries/radpdfprocessing/model/annotations-and-destinations.md
libraries/radpdfprocessing/model/form.md
libraries/radpdfprocessing/model/formsource.md
libraries/radpdfprocessing/model/path.md

New articles added to desribe the new classes. The related topics are updated.

Describe Form and FormSource classes

---

libraries/radpdfprocessing/model/interactive-forms/acroform.md
libraries/radpdfprocessing/model/interactive-forms/formfieldcollection.md

Described the FormFieldCollection class and its new methods.

---

libraries/radwordsprocessing/model/headers-footers.md

Update Note for Visualization of headers and footers >> Section.HeaderTopMargin and Section.FooterBottomMargin.

Visualization of headers and footers

---

libraries/radspreadprocessing/features/formulas/functions.md

The Functions topic is updated to describe the new supported functions in SpreadProcessing.

Add information about the newly implemented functions.

---

libraries/radpdfprocessing/overview.md

More features listed with links to the related topics

Update Overview topic for PdfProcessing

---

_assets/stylesheets/styles.css
_plugins/markdown_processor.rb

Move anchor class to header elements
Change edit link position to fixed

Fix anchors

---

libraries/radwordsprocessing/editing/import-document-element.md

If I've understood correctly, it's an element from the **source** document that should be passed to the Import() method?

Fix up an error in the example

---

libraries/radwordsprocessing/model/run.md

Added more detail for the FontSize property (taken directly from the RadPDFProcessing's TextFragment).

Update of the Run element description

---

libraries/radspreadprocessing/features/worksheetpagesetup.md

TryInsertHorizontalPageBreak is duplicated.

---

libraries/radpdfprocessing/getting-started.md
libraries/radspreadstreamprocessing/getting-started.md
libraries/radwordsprocessing/cross-platform.md
libraries/radwordsprocessing/getting-started.md
libraries/radwordsprocessing/sdk-examples.md
libraries/radziplibrary/gettingstarted.md

Information about .NET Standard binaries added.

Getting started articles improvements

---

libraries/radspreadprocessing/working-with-rows-and-columns/insert-and-remove.md

The old code was somewhat misguiding.

Updated the code snippets for Removing Rows and Columns

---

.gitignore
libraries/radpdfprocessing/features/flatten-form-fields.md

The docs for the FlattentFormFields feature

Flatten form fields docs

---

libraries/radpdfprocessing/formats-and-conversion/converting-other_formats.md

245863 PdfProcessing: Add info about conversion from flow formats to PDF

added new conversion article

---

libraries/radpdfprocessing/cross-platform/images.md

Edited code sample as per the https://github.com/telerik/document-processing-docs/pull/262 Pull Request from MagickImage

Updated MagickImage code sample as per their PR

---

knowledge-base/pdfprocessing-rotate-jpeg-with-orientation-set-in-metadata.md

Handle the import of JPEG images with orientation set in their metadata different than 0 (normal)

New KB example

---

libraries/radpdfprocessing/formats-and-conversion/pdf/pdfformatprovider/settings.md
libraries/radwordsprocessing/changes-and-backward-compatibility/backward-compatibility.md
libraries/radwordsprocessing/concepts/fields/fields.md
libraries/radwordsprocessing/concepts/fields/section.md
libraries/radwordsprocessing/concepts/fields/sectionpages-field.md

Applied feedback

---

libraries/radspreadprocessing/changes-and-backward-compatibility/backward-compatibility.md

adding obsoleted members

---

libraries/radwordsprocessing/concepts/fields/ta-field.md
libraries/radwordsprocessing/concepts/fields/tc-field.md
libraries/radwordsprocessing/concepts/fields/toa-field.md
libraries/radwordsprocessing/concepts/fields/toc-field.md

Added more info.

---

libraries/radspreadstreamprocessing/getting-started.md

The gettign started guide contained some awkward phrasing. Hopefully, this improves it.

Improved the grammar of the getting started guide

---

libraries/radpdfprocessing/features/search.md

Added search article

---

libraries/radspreadprocessing/changes-and-backward-compatibility/backward-compatibility.md
libraries/radspreadprocessing/features/charts/series.md

Removed void Add(T) mehtod of Series Collection

Removed void Add(T) mehtod of Series Collection

---

libraries/radwordsprocessing/model/imageinline.md

Updated code

---

libraries/radpdfprocessing/formats-and-conversion/pdf/pdfformatprovider/settings.md

add new export settings

---

libraries/radwordsprocessing/formats-and-conversion/rtf/rtfformatprovider.md
libraries/radwordsprocessing/formats-and-conversion/word-file-formats/doc/docformatprovider.md
libraries/radwordsprocessing/formats-and-conversion/word-file-formats/docx/docxformatprovider.md

Refactored code samples and added usings.

Refactored code samples and added usings

---

libraries/radpdfprocessing/formats-and-conversion/pdf/pdfformatprovider/settings.md

deleted ImageFilterTypes.DCTDecode from ImageCompression section

deleted ImageFilterTypes.DCTDecode from ImageCompression section

---

libraries/radwordsprocessing/editing/radflowdocumenteditor.md

Added missing method

---

libraries/radspreadprocessing/features/charts/using-charts.md
libraries/radspreadprocessing/features/shapes-and-images.md

Changed obsolete collection

---

libraries/radpdfprocessing/formats-and-conversion/pdf/pdfstreamwriter/pdfstreamwriter.md

Added new option

---

libraries/radpdfprocessing/formats-and-conversion/pdf/pdfformatprovider/settings.md
libraries/radpdfprocessing/formats-and-conversion/pdf/pdfstreamwriter/pdfstreamwriter.md

Added new compression method

---

libraries/radpdfprocessing/formats-and-conversion/pdf/pdfformatprovider/settings.md

Added image filter type DCTDecode

Added image filter type DCTDecode and updated all image filter types

---

libraries/radpdfprocessing/model/annotations/stamp.md

Removed unused API in Stamp.md
